# config.yml
local_backend: true

# live
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: '_uploads'
public_folder: '/uploads' # The src attribute for uploaded media will begin with /images/uploads
